"""add news table

Revision ID: 340dd1d528ca
Revises: 350dc0f58e63
Create Date: 2023-05-11 11:51:42.684604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340dd1d528ca'
down_revision = '350dc0f58e63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('short_desc', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('comment_avg_hour', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_item')
    # ### end Alembic commands ###
