"""add chat_id to Subscriber table

Revision ID: 372f964eb1ad
Revises: 51acb60bcc78
Create Date: 2023-05-01 19:05:28.505468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372f964eb1ad'
down_revision = '51acb60bcc78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscriber', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriber', type_='foreignkey')
    op.drop_column('subscriber', 'chat_id')
    # ### end Alembic commands ###
