"""add time for sent news

Revision ID: 3baa76aafd45
Revises: ac4ab8670f9c
Create Date: 2025-05-31 13:15:54.660171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baa76aafd45'
down_revision = 'ac4ab8670f9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_item_sent', sa.Column('sent_time_utc', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_item_sent', 'sent_time_utc')
    # ### end Alembic commands ###
