"""add time for subscribers

Revision ID: a05b570ce502
Revises: 3baa76aafd45
Create Date: 2025-05-31 20:32:48.102715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05b570ce502'
down_revision = '3baa76aafd45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('subscribed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'subscribed_at')
    # ### end Alembic commands ###
