"""add news_item_sent table

Revision ID: ac4ab8670f9c
Revises: 340dd1d528ca
Create Date: 2023-05-17 09:34:16.380372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4ab8670f9c'
down_revision = '340dd1d528ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_item_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_item_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id', 'chat_id', name='unique_news_item_id_and_chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_item_sent')
    # ### end Alembic commands ###
