"""add game type

Revision ID: e0a7a347e2c7
Revises: b561ba729112
Create Date: 2025-07-22 13:05:40.527177

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm

from hltv_upcoming_events_bot import domain
from hltv_upcoming_events_bot.db import GameType, NewsItem

# revision identifiers, used by Alembic.
revision = 'e0a7a347e2c7'
down_revision = 'b561ba729112'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.add_column('news_item', sa.Column('game_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news_item', 'game_type', ['game_type_id'], ['id'])
    # ### end Alembic commands ###

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # fill up game_type table
    cs2_game = GameType(name=str(domain.GameType.CS2))
    session.add(cs2_game)
    session.add(GameType(name=str(domain.GameType.DOTA2)))
    session.flush()

    # set game_type to CS2 to all existing news
    for ni in session.query(NewsItem):
        ni.game_type_id = cs2_game.id

    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_item', type_='foreignkey')
    op.drop_column('news_item', 'game_type_id')
    op.drop_table('game_type')
    # ### end Alembic commands ###
