"""add match stars

Revision ID: fe24f71e2ae3
Revises: 3869beb87ca1
Create Date: 2023-01-23 10:54:41.276911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe24f71e2ae3'
down_revision = '3869beb87ca1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('stars', sa.Enum('ZERO', 'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='matchstars'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'stars')
    # ### end Alembic commands ###
